# An example of ClusterConfig object using an existing VPC:
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: us-east-1

vpc:
  id: "vpc-0e9b8d754018f3dbc"  # (optional, must match VPC ID used for each subnet below)
  cidr: "10.40.0.0/16"       # (optional, must match CIDR used by the given VPC)
availabilityZones: ["us-east-1a"]
subnets: ["subnet-056c011dcadbb4283"]
  # subnets:
  #   # must provide 'private' and/or 'public' subnets by availability zone as shown
  #   public:
  #     # us-east-1b:
  #     #   id: "subnet-060dd1184cc0d7b06"
  #     #   cidr: "10.40.16.0/20" # (optional, must match CIDR used by the given subnet)

  #     # us-east-1a:
  #     #   id: "subnet-056c011dcadbb4283"
  #     #   cidr: "10.40.0.0/20"  # (optional, must match CIDR used by the given subnet)

  #     # eu-north-1c:
  #     #   id: "subnet-00f71956cdec8f1dc"
  #     #   cidr: "192.168.0.0/19"   # (optional, must match CIDR used by the given subnet)

nodeGroups:
  - name: spot
    instanceType: m5.large
    desiredCapacity: 4
    ssh:
      publicKeyName: siva-key